from typing import Protocol

from src.ports.erosion_backend_port import ErosionBackendPort
from src.ports.robot_controller_port import RobotControllerPort


class IHardwareController(Protocol):
    @property
    def erosion_backend(self) -> ErosionBackendPort: ...

    @property
    def robot_controller(self) -> RobotControllerPort: ...

    def set_coord_pos(self, x: float, y: float, z: float) -> None: ...
    def set_joint_pos(self, joints: list[float]) -> None: ...
    def set_erosion(self, state: bool) -> None: ...
    def set_water(self, state: bool) -> None: ...
    def pump_control_one(self) -> None: ...
    def pump_control_two(self) -> None: ...
    def set_speed(self, v: int) -> None: ...
    def emergency_stop(self) -> None: ...
