from typing import Protocol


class RobotControllerPort(Protocol):
    current_x: float
    current_y: float
    current_z: float

    def set_coord_pos(self, x: float, y: float, z: float) -> None: ...
    def set_joint_pos(self, joints: list[float]) -> None: ...
    def set_speed(self, v: int) -> None: ...
    def emergency_stop(self) -> None: ...
