from typing import Protocol


class RobotControllerPort(Protocol):
    def move_xyz(self, dx: float, dy: float, dz: float) -> None: ...
    def set_coord_pos(self, x: float, y: float, z: float) -> None: ...
    def return_to_zero_xyz(self) -> None: ...
